Task_1_2_1
Krookikk/OOP pull request #5
Opened 2023-10-19 16:57 UTC by Krookikk

2023-10-21 15:52 UTC, BIGNIKi requested changes

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +    public Queue<NewTree<Type1>> queue;
Поля не могут быть публичными. Нельзя так делать.

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +    public BFSIterator(NewTree<Type1> root) {
На класс не написаны тесты.

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +        this.oldCount = root.count;
Довольно забавно видеть, что здесь ты разыменовываешь переменную root, а потом, на следующей же строке, проверяешь, что она null :)
Если передадут null в конструктор, у тебя при попытке разыменования уже всё упадет.

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +public class NewTree<Type1> {
NewTree не реализует интерфейс Iterable. А значит и не предоставляет стандартный механизм итерирования

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +public class NewTree<Type1> {
Вопрос к названию: почему new? Где old?

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/DFSIterator.java
> +public class DFSIterator<Type1> implements Iterator<NewTree<Type1>> {
Здесь те же замечания, что и у BFS

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public int count;
Публичные поля - плохо.

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public NewTree(Type1 data){
А если null передали?

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public NewTree<Type1> addChild(Type1 data){
А если null? Странно делать ноду дерева, которая хранит null. Создайте свой класс исключения и кидайте его в таком случае.

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public NewTree<Type1> addChild(NewTree<Type1> Child){
Тоже о null подумай

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public void remove(){
Здесь что-то совсем странно происходит.
Почему вдруг children стало null? Зачем так?

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +public class NewTree<Type1> {
Добавить метод удаления поддерева

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +public class NewTree<Type1> {
Добавить toString

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +        if (obj == null || this == null || this.getClass() != obj.getClass()) {
this никогда не будет равно null. Если бы текущий объект был null, equals на нем невозможно было бы вызвать

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +        NewTree<Type1> obj2 = (NewTree<Type1>) obj;
Вот так лучше делать
var obj2 = (NewTree<?>) obj;
Компилятор во время исполнения не знает, что такое Type1, поэтому на unchecked cast ругается

2023-10-21 15:52 UTC, BIGNIKi commented on Task_1_2_1/src/test/java/org/example/NewTreeTest.java
> +public class NewTreeTest {
Тестов совсем мало, надо больше делать.
foreach`и проверять, итераторы проверять и прочее

2023-10-21 15:58 UTC, BIGNIKi requested changes

2023-10-21 15:58 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +        if (oldCount != myTree.count){
А если myTree будет долгоживущим объектом и переменная myTree.count переполнится, а потом и вовсе снова станет равной oldCount? Как можно избежать такую проблему?
Переделывать не обязательно, можно будет просто поделиться со мной идеями.

2023-10-25 14:33 UTC, Krookikk commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +public class NewTree<Type1> {
New потому что при создании нового дерева мы используем этот класс. Руководствовалась такой логикой

2023-10-26 08:19 UTC, BIGNIKi requested changes

2023-10-26 08:19 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BfsIterator.java
> +    public Queue<NewTree<Type1>> getQueue() {
Все поля надо писать сверху файла, потом геттеры / сеттеры, потом конструкторы, потом остальные методы.

2023-10-26 08:19 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BfsIterator.java
> +    public void setQueue(Queue<NewTree<Type1>> queue) {
Зачем столько лишних геттеров и сеттеров, если ими никто не пользуется? Если они никому не нужны?

2023-10-26 08:19 UTC, BIGNIKi commented on Task_1_2_1/src/test/java/org/example/BfsIteratorTest.java
> +        var a = new DfsIterator<String>(tree1);
В BFS тестовом классе тестировать DFS - не находишь странным?

2023-10-26 08:19 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/NewTree.java
> +    public void remove() {
Добавить удаление элемента

2023-11-08 06:07 UTC, BIGNIKi approved these changes
Принял

2023-11-11 16:27 UTC, merged